"""empty message

Revision ID: 30d8d5c25cd6
Revises: 24ef4c07c80b
Create Date: 2023-02-26 13:25:39.702489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30d8d5c25cd6'
down_revision = '24ef4c07c80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.alter_column('code_distributor',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=40),
               existing_nullable=True)

    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.alter_column('code_manufacturer',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=40),
               existing_nullable=True)

    with op.batch_alter_table('outlet', schema=None) as batch_op:
        batch_op.alter_column('code_outlet',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlet', schema=None) as batch_op:
        batch_op.alter_column('code_outlet',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)

    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.alter_column('code_manufacturer',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)

    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.alter_column('code_distributor',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
